### ISSUE TITLE
ROS and Conda

### ISSUE THREAD

**Issue by IrvingF7** [leggedrobotics/radiance_field_ros#7]
Hi! 

Thank you for opening the codebase!

I have a question regarding Conda ROS integration, and it is not specifically tied to this repo but more of a general question.

My experience is mostly with ROS2 so maybe I am missing something from ROS1, but as I understand it, ROS1/2 has a strong dependency on Ubuntu's system Python. 

How do I let ROS access a specific Conda environment's installed packages? According to this [issue in the ROS2 repo](https://github.com/ros2/ros2/issues/1094), even using Python's native `venv` has some incompatibility sometimes, and ROS2's [official doc](https://docs.ros.org/en/jazzy/How-To-Guides/Using-Python-Packages.html) also stated that Conda is largely incompatible with ROS2

Looking forward to your insight! Thank you for your time

**Comment by maxwildersmith** [comment]
Hey there!

Unfortunately most of my work (including this repo) is targeted at ROS 1, so I'm not entirely up to date with the ROS 2 spec. That being said it is possible in ROS 1 to use venvs through the proper shebang, or workspace/package configuration. Unfortunately that leads to a bit of a mess with some packages being apt/system installed and others coming from conda/pip within the environment. Particularly when being run through ROS via things like `roslaunch`/`rosrun` (or `ros2 run` for ROS 2).

This is why we tried to make the system run/install in a more pythonic manner with a CLI similar to NerfStudio via [Tyro](https://brentyi.github.io/tyro/). This way we know which python version is being run and can avoid the overhead of ambiguities from ROS. 

Under this system there are 2 main things we still need from ROS, the message/service definitions, and the subscriber
We do however need a workspace to define the messages/services for render requests, and to make sure that the python environment has rospy installed in order to create the publishers and subscribers. By sourcing the workspace, we run things from a custom environment that extends the ROS environment, instead of trying to run a ROS environment which extends the conda environment. 

Either way the setup and install of complex environments like NerfStudio with ROS systems is often tricky. Ideally in the future we can release this as a Docker image for even faster deployment, although in the short term we are looking at creating an install option such that the offline command can be run from ROS without NerfStudio.

Hope this helps clear things up a bit!

**Comment by maxwildersmith** [comment]
Hey there! 

Did this answer your questions?

**Comment by IrvingF7** [comment]
Hi Maximum! Thank you so much for your time and detailed answer, and I apologize for not responding in a more timely manner.

I think you have made things abundantly clear to me, except for this sentence.

"By sourcing the workspace, we run things from a custom environment that extends the ROS environment, instead of trying to run a ROS environment which extends the conda environment."

That being said, please feel free to respond whenever it is convenient for you

**Comment by maxwildersmith** [comment]
No problem! Just returning from holidays and trying to clear up tickets.

When you are working with any custom environments, there's usually a base environment thats getting extended, this could be something simple like your bash environment which is loading in certain settings like what `PATH` to use when looking up commands, or what `USER` is currently accessing the shell. When you create a new environment you want to extend this base system by adding a new list of variables being set/overridden.

In the case of conda this base environment is some python installation which redirects `python` to the proper version and can add some executables to the `PATH` that were installed with python like pip. With ROS this is the base ROS environment found in /opt/ros/<distro>. These two base environments will have a different set of priorities of where to look when calling a command like `python`. 

So by extending the ROS workspace we are saying "using the python from conda, and anything that doesn't exist in conda/fails to look up here, use the ROS paths", if we instead built the ROS system on top of a conda environemnt the order would be "ROS paths first, then conda installed variables" which sometimes works, but some ROS things might expect a different version of python that was suposed to be linked with ROS and is now getting misdirected via conda.

Hope this helps!

**Comment by IrvingF7** [comment]
Thank you so much for this detailed answer. This completely cleaned things up for me. Thank you for your contribution to the community!
